package net.tclproject.rpgstamina;

import java.util.Collections;
import java.util.Random;

import cpw.mods.fml.common.event.FMLServerStartingEvent;
import net.tclproject.rpgstamina.mechanics.command.Command;
import net.tclproject.rpgstamina.client.GuiHealthStamina;
import net.tclproject.rpgstamina.config.Config;
import net.tclproject.rpgstamina.network.Network;

import cpw.mods.fml.common.FMLCommonHandler;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import net.minecraft.client.Minecraft;
import net.minecraft.init.Items;
import net.minecraft.launchwrapper.Launch;
import net.minecraft.util.EnumChatFormatting;
import net.minecraftforge.common.MinecraftForge;


@Mod(name = ModProperties.NAME, modid = ModProperties.MODID, version = ModProperties.VERSION, guiFactory = ModProperties.GUI_FACTORY_CLASS, useMetadata = true, dependencies = "required-after:MysteriumLib")
public class RPGStamina {

    @Instance(ModProperties.MODID)
    public static RPGStamina INSTANCE;

    public static EventHandler EVENT_HANDLER;
    public static boolean isRunningInDevEnvironment;

    @Mod.EventHandler
    public void preInit(FMLPreInitializationEvent event) {
    // Event called at the beginning of the mod's organisation.

        INSTANCE = this;

        // Registers the event handler.
        EVENT_HANDLER = new EventHandler();
        MinecraftForge.EVENT_BUS.register(EVENT_HANDLER);
        FMLCommonHandler.instance().bus().register(EVENT_HANDLER);

        Config.configFolder = event.getModConfigurationDirectory().toString(); // Sets the config folder

        makeFancyModInfo(event); // Creates the nice looking mod info page.
    }

    public void makeFancyModInfo(FMLPreInitializationEvent event) {
    // The following will overwrite the mcmod.info file so the info page looks good.
    // Adapted from Jabelar's Magic Beans and AstroTibs's OptionsEnforcer.

        // This will stop Forge from complaining about missing mcmod.info (just in case i forget it).
        event.getModMetadata().autogenerated = false;

        event.getModMetadata().name = ModProperties.COLORED_NAME; // Mod name
        event.getModMetadata().version = ModProperties.COLORED_VERSION; // Mod version
        event.getModMetadata().credits = ModProperties.CREDITS; // Mod credits

        // Author list
        event.getModMetadata().authorList.clear();
        Collections.addAll(event.getModMetadata().authorList, ModProperties.AUTHORS);

        event.getModMetadata().url = ModProperties.COLORED_URL; // Mod URL

        // Mod description
        event.getModMetadata().description = ModProperties.DESCRIPTION + "\n\n" + EnumChatFormatting.DARK_GRAY + EnumChatFormatting.ITALIC +
                                             ModProperties.SPLASH_OF_THE_DAY[(new Random()).nextInt(ModProperties.SPLASH_OF_THE_DAY.length)] ;

        if (ModProperties.LOGO != null) event.getModMetadata().logoFile = ModProperties.LOGO; // Mod logo
    }



    @Mod.EventHandler
    public void init(FMLInitializationEvent event) {
    // Event called in the middle of the mod's initialisation.

        Network.init();
    }
    
    @Mod.EventHandler
    public void postInit(FMLPostInitializationEvent event) {
    // Event called at the end of the mod's initialisation.

    	isRunningInDevEnvironment = (Boolean)Launch.blackboard.get("fml.deobfuscatedEnvironment"); // Creates a boolean to check if we're running in a dev environment.

        Config.init(); // Creates the config

        if (Config.enableBlazeRodRender) Items.blaze_rod.setFull3D(); // Makes the blaze rod item 3D (Might move to another mod as it's not related).

        // Registers the HUD bar if on the client side.
    	if (FMLCommonHandler.instance().getEffectiveSide().isClient()) MinecraftForge.EVENT_BUS.register(new GuiHealthStamina(Minecraft.getMinecraft()));
    }

    @Mod.EventHandler
    public void serverStart(FMLServerStartingEvent event) {
    // Event called while starting the server.
    // Used to register the custom command.

        if (Config.commandEnabled) event.registerServerCommand(new Command());
    }
}
